controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_doc:
    path: /api-platform/documentation
    controller: api_platform.swagger_ui.action
api_login_check:
    path: /api-platform/login_check

